# Use an official Python runtime as a parent image
FROM ubuntu:14.04

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get -y install curl \
  default-jre default-jdk
